parkwoods/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('parkwoods_app.urls', namespace='parkwoods_app')),
]

parkwoods_app/urls.py
""" Define URL patterns for parkwoods_app"""

from django.urls import path

from . import views
app_name = 'parkwoods_app'

urlpatterns = [
    # Home page
    path('', views.index, name='index'),
    # page that shows all topics
    path('topics/', views.topics, name='topics'),
    # Detail page for a single topic
    path('topics/<int:topic_id>/', views.topic, name='topic'),
    # Page for a new topic
    path('new_topic/', views.new_topic, name='new_topic'),
    # Page for adding a new entry
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
    # Page for editing an entry
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
    # Page for rosters
    path('rosters/', views.rosters, name='rosters'),
    # Page for awards
    path('awards/', views.awards, name='awards'),
    # Page for videos
    path('videos/', views.videos, name='videos'),
    # Page for standings
    path('standings/', views.standings, name='standings'),
    # Page for playoff standings
    path('standings_playoff/', views.standings_playoff, name='standings_playoff'),
    # Page for semi-finals standings
    path('standings_semi/', views.standings_semi, name='standings_semi'),
    # Page for finals standings
    path('standings_finals/', views.standings_finals, name='standings_finals'),
    # Page for schedule
    path('schedule/', views.schedule, name='schedule'),
    # Page for playoff schedule
    path('schedule_playoff/', views.schedule_playoff, name='schedule_playoff'),
    # Page for semi-finals schedule
    path('schedule_semi/', views.schedule_semi, name='schedule_semi'),
    # Page for finals schedule
    path('schedule_finals/', views.schedule_finals, name='schedule_finals'),    
    
    # Page for about me
    path('aboutme/', views.aboutme, name='aboutme'),
]

users/urls.py
""" Define URL patterns for users"""

from django.urls import path, include
from . import views

app_name = 'users'

urlpatterns = [
    # Include default auth urls.
    path('', include('django.contrib.auth.urls')),
    # Registration page.
    path('register/', views.register, name='register'),
]

parkwoods_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _
from datetime import datetime

# Create your models here.

class Topic(models.Model):
    """ topic user is learning """
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.text


class Entry(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        return f"{self.text[:50]}..."


class Division(models.TextChoices):
    TYKE = 'TK', _('Tyke')
    MINOR_NOVICE = 'MN', _('Minor Novice')
    NOVICE = 'NV', _('Novice')
    MINOR_ATOM = 'MA', _('Minor Atom')
    ATOM = 'AT', _('Atom')
    MINOR_PEEWEE = 'MP', _('Minor Peewee')
    PEEWEE = 'PW', _('Peewee')
    MINOR_BANTAM = 'MB', _('Minor Bantam')
    BANTAM = 'BT', _('Bantam')
    MINOR_MIDGET = 'MM', _('Minor Midget')
    MIDGET_JUNIOR = 'MJ', _('Midget Junior')
    MIDGET_SENIOR = 'MS', _('Midget Senior')
    UNDER_21 = 'UD', _('Under 21')


class Season(models.TextChoices):
    FINAL_2020 = 'FN20', _('FINAL 2020')
    SEMI_FINAL_2020 = 'SF20', _('SEMI-FINAL 2020')
    PLAYOFF_2020 = 'PL20', _('Playoff 2020')
    WINTER_2020 = 'WY20', _('Winter Season 2020')
    FALL_2019 = 'FY19', _('Fall Season 2019')    


class Level(models.TextChoices):
    TIER1 = 'T1', _('Tier 1')
    TIER2 = 'T2', _('Tier 2')
    TIER3 = 'T3', _('Tier 3')
    
class Group(models.TextChoices):
    GROUP_A = 'G1', _('Group A')
    GROUP_B = 'G2', _('Group B')


class Schedule(models.Model):
    game_dt = models.DateField()
    game_time = models.TimeField()
    away = models.CharField(max_length=30)
    home = models.CharField(max_length=30)
    score = models.CharField(max_length=5)
    venue = models.CharField(max_length=50)
    date_added = models.DateTimeField(auto_now_add=True)

    division = models.CharField(
        max_length=2,
        choices=Division.choices,
        default=Division.MIDGET_SENIOR
    )

    season = models.CharField(
        max_length=4,
        choices=Season.choices,
        default=Season.WINTER_2020
    )

    level = models.CharField(
        max_length=2,
        choices=Level.choices,
        default=Level.TIER1
    )

    def save(self, *args, **kwargs):
        self.date_added = datetime.now()
        super().save(*args, **kwargs)
        
    def __str__(self):
        return self.away + '-' + self.home

class Standings(models.Model):
    name = models.CharField(max_length=30)
    gp = models.IntegerField(editable=False, default=0)
    pts = models.IntegerField(editable=False, default=0)
    wins = models.IntegerField(default=0)
    loses = models.IntegerField(default=0)
    ties = models.IntegerField(default=0)
    gf = models.IntegerField(default=0)
    ga = models.IntegerField(default=0)
    gfavg = models.DecimalField(
        max_digits=5, decimal_places=4, editable=False, default=0.0000)
    date_added = models.DateTimeField(auto_now_add=True)
    
    division = models.CharField(
        max_length=2,
        choices=Division.choices,
        default=Division.MIDGET_SENIOR
    )

    season = models.CharField(
        max_length=4,
        choices=Season.choices,
        default=Season.WINTER_2020
    )

    level = models.CharField(
        max_length=2,
        choices=Level.choices,
        default=Level.TIER1
    )    
    pl_group = models.CharField(
        max_length=2,
        choices=Group.choices,
        default=None, 
        blank=True,
        null=True
    )

    def save(self, *args, **kwargs):
        self.date_added = datetime.now()
        self.pts = self.wins*2 + self.ties
        if self.gf + self.ga == 0:
            self.gfavg = 0.0
        else:
            self.gfavg = self.gf / (self.gf + self.ga)
        self.gp = self.wins + self.ties + self.loses
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name

parkwoods_app/forms.py
from django import forms
from .models import Topic, Entry


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        lables = {'text': ''}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': 'Entry:'}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

parkwoods_app/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
import datetime

from .models import Topic, Entry, Standings, Schedule
from .forms import TopicForm, EntryForm


def index(request):
    """The home page."""
    return render(request, 'parkwoods_app/index.html')


def rosters(request):
    """The rosters page."""
    return render(request, 'parkwoods_app/rosters.html')

def awards(request):
    """The awards page."""
    return render(request, 'parkwoods_app/awards.html')


def videos(request):
    """The video page."""
    return render(request, 'parkwoods_app/videos.html')


def standings(request):
    """Show all standings."""    
    standings = Standings.objects.filter(season='WY20').order_by('-pts', '-wins', '-gfavg')
    context = {'standings': standings}
    return render(request, 'parkwoods_app/standings.html', context)
    
def standings_playoff(request):
    """Show all standings."""
    standings = Standings.objects.filter(pl_group='G1').order_by('-pts', '-wins', '-gfavg')
    groupB = Standings.objects.filter(pl_group='G2').order_by('-pts', '-wins', '-gfavg')
    context = {'standings': standings, 'groupB': groupB}
    return render(request, 'parkwoods_app/standings_playoff.html', context)
    
def standings_semi(request):
    """Show all standings."""
    standings = Standings.objects.filter(season='SF20').order_by('-pts', '-wins', '-gfavg')
    context = {'standings': standings}
    return render(request, 'parkwoods_app/standings_semi.html', context)
    
def standings_finals(request):
    """Show all standings."""
    standings = Standings.objects.filter(season='FN20').order_by('-pts', '-wins', '-gfavg')
    context = {'standings': standings}
    return render(request, 'parkwoods_app/standings_finals.html', context)

def schedule(request):
    """The schedule page."""
    schedule = Schedule.objects.filter(season='WY20').order_by('game_dt', 'game_time')    
    context = {'schedule': schedule}
    return render(request, 'parkwoods_app/schedule.html', context)
    
def schedule_playoff(request):
    """The schedule page."""
    schedule = Schedule.objects.filter(season='PL20').order_by('game_dt', 'game_time')    
    context = {'schedule': schedule}
    return render(request, 'parkwoods_app/schedule_playoff.html', context)
    
def schedule_semi(request):
    """The schedule page."""
    schedule = Schedule.objects.filter(season='SF20').order_by('game_dt', 'game_time')    
    context = {'schedule': schedule}
    return render(request, 'parkwoods_app/schedule_semi.html', context)
    
def schedule_finals(request):
    """The schedule page."""
    schedule = Schedule.objects.filter(season='FN20').order_by('game_dt', 'game_time')    
    context = {'schedule': schedule}
    return render(request, 'parkwoods_app/schedule_finals.html', context)


def aboutme(request):
    """The about me page for Learning Log."""
    return render(request, 'parkwoods_app/aboutme.html')

def topics(request):
    """Show all topics."""
    topics = Topic.objects.order_by('date_added')
    context = {'topics': topics}
    return render(request, 'parkwoods_app/topics.html', context)


def topic(request, topic_id):
    """Show a single topic and all its entries."""
    topic = Topic.objects.get(id=topic_id)
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'parkwoods_app/topic.html', context)


@login_required
def new_topic(request):
    """Add a new topic."""
    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = TopicForm()
    else:
        # POST data submitted; process data.
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return redirect('parkwoods_app:topics')

    # Display a blank or invalid form.
    context = {'form': form}
    return render(request, 'parkwoods_app/new_topic.html', context)


@login_required
def new_entry(request, topic_id):
    """Add a new entry for a particular topic."""
    topic = Topic.objects.get(id=topic_id)

    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = EntryForm()
    else:
        # POST data submitted; process data.
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.owner = request.user
            new_entry.save()
            return redirect('parkwoods_app:topic', topic_id=topic_id)

    # Display a blank or invalid form.
    context = {'topic': topic, 'form': form}
    return render(request, 'parkwoods_app/new_entry.html', context)


@login_required
def edit_entry(request, entry_id):
    """Edit an existing entry."""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic

    if request.method != 'POST':
        # Initial request; pre-fill form with the current entry.
        form = EntryForm(instance=entry)
    else:
        # POST data submitted; process data.
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.owner = request.user
            new_entry.date_added = datetime.datetime.now()
            new_entry.save()
            return redirect('parkwoods_app:topic', topic_id=topic.id)

    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'parkwoods_app/edit_entry.html', context)

parkwoods_app/templates/parkwoods_app/aboutme.html
{% extends "parkwoods_app/base.html" %}

{% block page_header %}
{% load static %}
<div class="pb-2 mb-2 border-bottom">
  <div class="jumbotron">
    <div class="row">
      <div class="col-md-4">
        <div class="card mb-4 shadow-sm" align="center">
          <img class="img-fluid" src="{% static "parkwoods_app/aboutme.jpg" %}" alt="aboutme">
        </div>
      </div>
      <div class="col-md-8">
        <h1 class="display-4" align="center"><b>About Jesse Li</b></h1>
        <p>
          I am a first-year student studying computer science at the <a href="https://uwaterloo.ca/" target="_blank">  University of Waterloo
            </a>  (1B term) in Waterloo, Ontario, Canada. 
        </p>

        <p>
          I have always had a strong passion for hockey. I played at the <a href="http://www.parkwoodshockey.com/" target="_blank">Parkwoods Hockey League</a> for eleven years, and
          I was a part of their select team for eight years. Other hobbies of mine include making and editing videos, travelling, and listening to music.
        </p>

        <p>
          I created this website using the Python programming language, HTML and the Django web framework to showcase my hockey experience. 
		      Here, you will be able to see our team's short video clips, standings/schedules and various trophy winnings. If you are registered,
          you can also create a topic and share your thoughts with others.
        </p>

        <p>
          This pandemic has been a challenge for everybody. Although studying online has been difficult at times, I have persevered and continued to work my hardest. 

        </p>
        <p>
          I am currently seeking an internship for the spring 2021 term. 
        </p>
      </div>
    </div>
  </div>
</div>
{% endblock page_header %}

parkwoods_app/templates/parkwoods_app/awards.html
{% extends "parkwoods_app/base.html" %}


{% block page_header %}
<section class="jumbotron text-center">
  <div class="container">
    <h1> Medals and Trophies </h1>
    <p>
      <a href="https://1drv.ms/u/s!AilqDLjqHaNaqwQBdhSH1VAua8uX?e=vFqPu8" class="btn btn-primary my-2" target="_blank">More photos &raquo;</a>
    </p>
  </div>
</section>
{% endblock page_header %}

{% block content %}
{% load static %}
<div class="album py-5 bg-light">
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <div class="card mb-4 shadow-sm">
          <a href="https://1drv.ms/u/s!AilqDLjqHaNaqwtCMed6bc6sFGXQ" target="_blank" ><img class="img-fluid" src="{% static "parkwoods_app/JesseTrophy-1.jpg" %}" alt="JesseTrophy-1"></a>
          <div class="card-body">
            <p class="card-text">NYHL All Stars 2013 ~ 2015</p>
          </div>
        </div>
      </div>      
      <div class="col-md-4">
        <div class="card mb-4 shadow-sm">
          <a href="https://1drv.ms/u/s!AilqDLjqHaNaqwo0V0otFVrlpVb2" target="_blank" ><img class="img-fluid" src="{% static "parkwoods_app/JesseTrophy-13.jpg" %}" alt="JesseTrophy-13"></a>
          <div class="card-body">
            <p class="card-text">Wayne Gretzky's Signature</p>

          </div>
        </div>
      </div>
	  <div class="col-md-4">
        <div class="card mb-4 shadow-sm">
          <a href="https://1drv.ms/u/s!AilqDLjqHaNaqwxpRphTPle5_UZs" target="_blank" ><img class="img-fluid" src="{% static "parkwoods_app/JesseTrophy-2.jpg" %}" alt="JesseTrophy-2"></a>
          <div class="card-body">
            <p class="card-text">Ajax Tournament Champions, MVP 2014</p>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="card mb-4 shadow-sm">
          <a href="https://1drv.ms/u/s!AilqDLjqHaNaqwiMfO8UaINC8WDI" target="_blank" ><img class="img-fluid" src="{% static "parkwoods_app/JesseTrophy-11.jpg" %}" alt="JesseTrophy-11"></a>
          <div class="card-body">
            <p class="card-text">Various Tournaments, Skills Competition</p>

          </div>
        </div>
      </div>
      
      <div class="col-md-4">
        <div class="card mb-4 shadow-sm">
          <a href="https://1drv.ms/u/s!AilqDLjqHaNaqwaxqHzTbsl0JYoK" target="_blank" ><img class="img-fluid" src="{% static "parkwoods_app/JesseTrophy-8.jpg" %}" alt="JesseTrophy-8"></a>
          <div class="card-body">
            <p class="card-text">Shamrock Tournament, 2013 ~ 2019</p>

          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="card mb-4 shadow-sm">
          <a href="https://1drv.ms/u/s!AilqDLjqHaNaqwX2A-ImqX6c9dNz" target="_blank" ><img class="img-fluid" src="{% static "parkwoods_app/JesseTrophy-9.jpg" %}" alt="JesseTrophy-9"></a>
          <div class="card-body">
            <p class="card-text">Bradford Tournament, 2013 ~ 2017</p>

          </div>
        </div>
      </div>
	  <div class="col-md-4">
        <div class="card mb-4 shadow-sm">
          <a href="https://1drv.ms/u/s!AilqDLjqHaNaqw2O0WxULCDg5dua" target="_blank" ><img class="img-fluid" src="{% static "parkwoods_app/JesseTrophy-3.jpg" %}" alt="JesseTrophy-3"></a>
          <div class="card-body">
            <p class="card-text">Trophies from Parkwoods Hockey League</p>

          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="card mb-4 shadow-sm">
          <a href="https://1drv.ms/u/s!AilqDLjqHaNaqw4aPymf__wWPld7" target="_blank" ><img class="img-fluid" src="{% static "parkwoods_app/JesseTrophy-4.jpg" %}" alt="JesseTrophy-4"></a>
          <div class="card-body">
            <p class="card-text">North Toronto Tournament </p>

          </div>
        </div>
      </div>
	  <div class="col-md-4">
        <div class="card mb-4 shadow-sm">
          <a href="https://1drv.ms/u/s!AilqDLjqHaNaqwkDpsgwI96ZtpWE" target="_blank" ><img class="img-fluid" src="{% static "parkwoods_app/JesseTrophy-12.jpg" %}" alt="JesseTrophy-12"></a>
          <div class="card-body">
            <p class="card-text">Other Tournament Winnings </p>

          </div>
        </div>
      </div>
      
    </div>
  </div>
</div>


{% endblock content %}

parkwoods_app/templates/parkwoods_app/base.html
{% load bootstrap4 %}
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1,
    shrink-to-fit=no">
  <title>Parkwoods Senior Midget Stars</title>

  {% bootstrap_css %}
  {% bootstrap_javascript jquery='full' %}

</head>
{% load static %}

<body>

  <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
    <a class="navbar-brand" href="{% url 'parkwoods_app:index'%}"><img id="img-logo"
        src="{% static "parkwoods_app/parkwoods.png" %}" style="width: 36px; height: 36px;">Parkwoods Midget Senior
      Stars
    </a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
      aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span></button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item"><a class="nav-link" href="{% url 'parkwoods_app:topics'%}">Topics</a></li>
        <li class="nav-item"><a class="nav-link" href="{% url 'parkwoods_app:rosters'%}">Roster</a></li>
        <li class="nav-item"><a class="nav-link" href="{% url 'parkwoods_app:videos'%}">Video</a></li>
        <div class="dropdown">
          <a class="nav-link" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Standings</a></li>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <a class="dropdown-item" href="{% url 'parkwoods_app:standings'%}">Winter</a>
            <a class="dropdown-item" href="{% url 'parkwoods_app:standings_playoff'%}">Playoffs</a>
            <a class="dropdown-item" href="{% url 'parkwoods_app:standings_semi'%}">Semi-Finals</a>
            <a class="dropdown-item" href="{% url 'parkwoods_app:standings_finals'%}">Finals</a>
          </div>
        </div>  

        <div class="dropdown">
          <a class="nav-link" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Schedule</a></li>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <a class="dropdown-item" href="{% url 'parkwoods_app:schedule'%}">Winter</a>
            <a class="dropdown-item" href="{% url 'parkwoods_app:schedule_playoff'%}">Playoffs</a>
            <a class="dropdown-item" href="{% url 'parkwoods_app:schedule_semi'%}">Semi-Finals</a>
            <a class="dropdown-item" href="{% url 'parkwoods_app:schedule_finals'%}">Finals</a>
          </div>
        </div>
        
		<li class="nav-item"><a class="nav-link" href="{% url 'parkwoods_app:awards'%}">Medals & Trophies</a></li>
        <li class="nav-item"><a class="nav-link" href="{% url 'parkwoods_app:aboutme' %}">About Me</a></li>
      </ul>
      <ul class="navbar-nav ml-auto">
        {% if user.is_authenticated %}
        <li class="nav-item">
          <span class="navbar-text" }">Hello, {{ user.username }}.</span>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:register' %}">Register</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:login' %}">Log in</a></li>
        {% endif %}
      </ul>
    </div>

  </nav>

  <main role="main" class="container">

    {% block page_header %}{% endblock page_header %}


    {% block content %}{% endblock content %}
    <footer class="text-muted">
      <div class="container">
        <p class="float-right">
          <a href="#">Back to top</a>
        </p>
        <p><a href="{% url 'parkwoods_app:aboutme' %}">&copy; Jesse Li </a>2019 | Powered by <a href="http://www.python.org"
            target="_blank"> &reg; Python </a> <a href="https://www.djangoproject.com/" target="_blank"> &reg;
            Django</a> <a href="https://getbootstrap.com/" target="_blank"> &reg; Bootstrap 4<a
              href="http://www.heroku.com/" target="_blank"> &reg; Heroku</a>
        </p>
      </div>
    </footer>
  </main>


</body>

</html>

parkwoods_app/templates/parkwoods_app/edit_entry.html
{% extends "parkwoods_app/base.html" %}

{% block content %}
<div class="pb-2 mb-2 border-bottom">
</div>
<p><a href="{% url 'parkwoods_app:topic' topic.id %}">{{ topic }}</a></p>

<p>Edit entry:</p>

<form action="{% url 'parkwoods_app:edit_entry' entry.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name='submit'>Save Changes</button>
</form>

{% endblock content %}

parkwoods_app/templates/parkwoods_app/index.html
{% extends "parkwoods_app/base.html" %}

{% block page_header %}

<div class="pb-2 mb-2 border-bottom">
  <div class="jumbotron">
    <h1 class="display-3">A Passion for Junior hockey</h1>
    <p class="lead">
      The <a href="https://1drv.ms/v/s!AilqDLjqHaNauFRp-1QSoeV0PYor?e=kd7J0I" target="_blank">Parkwoods Midget Senior Stars</a> were established in 2009 and played at the Tier 1 Select level in the
      <a href="http://www.nyhl.on.ca" target="_blank">North York Hockey League </a>(NYHL) located in Toronto, Ontario, Canada. The majority of players played on this team
      for the entire duration of their youth hockey career. The team has made four NYHL Tier 1 Finals appearances, winning the
      championship in 2013. Parkwoods Hockey League encourages more ice time,
      hence this select team only has thirteen skaters and two goalies. The head coach (right first) is <b>Francis Cooke</b>
      and the assistant coaches are <b>James Cooke</b> (left first) and <b>Paul Magrath</b> (left second).
    </p>
    {% load static %}
    <img class="img-fluid" src="{% static "parkwoods_app/team.jpg" %}" alt="team">
	<a class="btn btn-lg btn-primary" href="{% url 'users:register' %}" role="button">Register &raquo;</a>
  </div>
</div>

{% endblock page_header %}

parkwoods_app/templates/parkwoods_app/new_topic.html
{% extends 'parkwoods_app/base.html' %}
{% block content %}
<div class="pb-2 mb-2 border-bottom">
</div>
<p>Add a new topic:</p>
<form action="{% url 'parkwoods_app:new_topic' %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Add Topic</button>
</form>
{% endblock content %}

parkwoods_app/templates/parkwoods_app/topic.html
{% extends 'parkwoods_app/base.html' %}

{% block page_header %}
<div class="pb-2 mb-2 border-bottom">
  <h3>{{ topic }}</h3>
</div>
{% endblock page_header %}

{% block content %}
<div>
  {% if user.is_authenticated %}
  <p>
    <a href="{% url 'parkwoods_app:new_entry' topic.id %}">Add new entry</a>
  </p>
  {% endif %}
  <ul>
    {% for entry in entries %}
    <div class="card mb-3">
      <h4 class="card-header">
        {{ entry.date_added|date:'M d, Y H:i' }} (by {{ entry.owner }})
        {% if user.is_authenticated and user.username == 'admin' %}
        <small><a href="{% url 'parkwoods_app:edit_entry' entry.id %}">edit entry</a></small>
        {% elif user.is_authenticated and entry.owner == request.user %}
        <small><a href="{% url 'parkwoods_app:edit_entry' entry.id %}">edit entry</a></small>
        {% endif %}
      </h4>
      <div class="card-body">
        {{ entry.text|linebreaks }}
      </div>
    </div>
    {% empty %}
    <p>There are no entries for this topic yet.</p>
    {% endfor %}
</div>
{% endblock content %}

parkwoods_app/templates/parkwoods_app/topics.html
{% extends "parkwoods_app/base.html" %}


{% block page_header %}
<div class="pb-2 mb-2 border-bottom">
  <h1>Topics</h1>
</div>
{% endblock page_header %}


{% block content %}
<div>
  <ul>
    {% for topic in topics %}
      <li><h3>
        <a href="{% url 'parkwoods_app:topic' topic.id %}">{{ topic }}</a>
      </h3></li>
    {% empty %}
      <li><h3>No topics have been added yet.</h3></li>
    {% endfor %}
  </ul>

  <h3><a href="{% url 'parkwoods_app:new_topic' %}">Add a new topic</a></h3>
</div>
{% endblock content %}